-- NSFW 0
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been arrested", 0);
INSERT INTO questions (question, sfw) VALUES ("Never have I ever sharted", 0);
INSERT INTO questions (question, sfw) VALUES ("Have you ever thought of your teacher sexually", 0);
INSERT INTO questions (question, sfw) VALUES ("Have you ever smelled someone else's hair", 0);
INSERT INTO questions (question, sfw) VALUES ("Never have I ever licked a pair of balls", 0);

INSERT INTO questions (question, sfw) VALUES ("Never have I gotten black out drunk", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever driven drunk", 0)
INSERT INTO questions (question, sfw) VALUES ("I've had sex in a public place... more than once", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been in an orgy", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever seen my best friend naked", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever masturbated in public", 0)

INSERT INTO questions (question, sfw) VALUES ("Never have I ever played a questions game before", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever peed in public", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever stolen from my place of work", 0)
INSERT INTO questions (question, sfw) VALUES ("I've been on more than one drug at once", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever gotten road head", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever got into a fight", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever streamed pornography", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever found a family member attractive...sexually", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever put a finger in my butthole", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been on the inside of a jail cell", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever broke into a building", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been mugged", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever picked my nose", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever drank alcohol off of a girls stomach", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever shat into a bag, set it on fire, and put it on someone's porch... never", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever put more than 3 fingers in someone's vagina", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever seen a fleshlight... what's a fleshlight?", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever read a newspaper all the way through", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever read more than 3 books", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever graduated from highschool", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever graduated from college", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever graduated", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever seen a bum masturbate", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever eaten a bug", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I had sex with my crush", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been on top of a car", 0)

INSERT INTO questions (question, sfw) VALUES ("Never have I walked in on my parents", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever bathed in a fountain", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever flown a plane", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I had sex... period", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I stopped thinking about my ex", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I had a blowjob", 0)
INSERT INTO questions (question, sfw) VALUES ("Never has anyone touched my privates", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been eaten out", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever given birth", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I had sex with someone twice my age", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever walked around my place naked", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I had down syndrome", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever looked so deeply into your eyes I came..actually I just came", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been married", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been divorced", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever had two parents", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever licked a human eyeball", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever said the word nig... yeah that word", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I gone commando", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever said fuck you to my boss", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever shot a gun", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever shot a 5 calibur rifle", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever word a dress", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I worn a pair of panties", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever had a handjob", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever licked an animal", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I had a penis", 0)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever peed on myself", 0)

INSERT INTO questions (question, sfw) VALUES ("Never have I", 1)


--SFW 1
INSERT INTO questions (question, sfw) VALUES ("Never have I ever eaten a ham sandwich", 1);
INSERT INTO questions (question, sfw) VALUES ("Never have I ever worn a dress", 1);
INSERT INTO questions (question, sfw) VALUES ("Never have I ever cut my own hair", 1);
INSERT INTO questions (question, sfw) VALUES ("Never have I ever driven my own car", 1);
INSERT INTO questions (question, sfw) VALUES ("Never have I ever worried about my weight", 1)

INSERT INTO questions (question, sfw) VALUES ("I've eaten cereal with something other than milk or water", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever check my car's oil", 1)
INSERT INTO questions (question, sfw) VALUES ("I've traveled to more than 5 countries", 1)
INSERT INTO questions (question, sfw) VALUES ("I've driven on the wrong side of the road", 1)
INSERT INTO questions (question, sfw) VALUES ("I've drank from a source of dirty water", 1)
INSERT INTO questions (question, sfw) VALUES ("I've lied to my boss to get the day off", 1)
INSERT INTO questions (question, sfw) VALUES ("I've cheated on a class final", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ridden a horse", 1)

INSERT INTO questions (question, sfw) VALUES ("Never have I drank from a fountain", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever bathed for more than an hour", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever watched someone else's pet", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever seen anime", 1)
INSERT INTO questions (question, sfw) VALUES ("I've never learned to draw", 1)
INSERT INTO questions (question, sfw) VALUES ("I can play the an instrument", 1)
INSERT INTO questions (question, sfw) VALUES ("I'm an awesome singer", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever hydroplaned", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever played the piano", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever copied someone else code", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever worked at place for more than a year", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I dreamed about going to the moon", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been on a plane", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I spoke spanish", 1)

INSERT INTO questions (question, sfw) VALUES ("Never have I ever been in a government building", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever been broke", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever worn a blanket as a cape", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I joined the military", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I used skype", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I used instagram", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I used snapchat", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I spoke french", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I laughed at a bad joke", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever played videogames", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I played magic the gathering the card game", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I ever pet a cow", 1)
INSERT INTO questions (question, sfw) VALUES ("Never have I slept under the stars", 1)

INSERT INTO questions (question, sfw) VALUES ("Never have I eaten red meat", 1)
